#include<cstdio>
#include<iostream>
#include<algorithm>
using namespace std;
int main()
{
	freopen("money.in","r",stdin);
	freopen("money.out","w",stdout);
	int t,a[10005],book=-2,i,j,cha=0,sum=0,n,k,x,sumb=0;
	scanf("%d",&t);
	for(i=1;i<=t;i++)
	{
		scanf("%d",&n);
		sum=n;
		for(j=1;j<=n;j++)
		{
			scanf("%d",&a[j]);
		}
		sort(a+1,a+n+1);
		for(j=1;j<=n;j++)
		{
			if(a[1]==1)
			{
				sum=1;
				break;
			}
			for(k=j;k<=n;k++)
			{
				if(a[k]>=0)
				{
					cha=a[k];
					while(cha<=a[n])
					{
						cha=cha+a[j];
						for(x=1;x<=n;x++)
						{
							if(cha==a[x])
							{
								a[x]=-1;
								sum--;
							}
						}
					}
				}
			}
		}
		for(j=1;j<=n;j++)
		{
			if(a[1]==1)
				break;
			sumb=0;
			if(a[j]>=0)
			{
				if(a[j]!=book)
				{
					book=a[j];
					for(x=1;x<=n;x++)
					{
						if(a[x]==book)
							sumb++;
					}
				}
			}
			if(sumb!=0)
				sum=sum-sumb+1;
		}
		printf("%d",sum);
		if(i!=t)
		printf("\n");
	}
	return 0;
}
